# Criar Relatório 1
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório de Desempenho Acadêmico",
  "description": "Este relatório contém a análise do desempenho acadêmico dos alunos do ensino fundamental no 1º semestre.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 2
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório de Frequência Escolar",
  "description": "Relatório detalhando a frequência dos alunos durante o 1º semestre de 2024.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 3
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório de Atividades Extracurriculares",
  "description": "Este relatório cobre todas as atividades extracurriculares realizadas pelos alunos durante o ano de 2024.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 4
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório de Avaliação de Professores",
  "description": "Avaliação semestral de desempenho dos professores baseada em feedbacks de alunos e pais.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 5
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório de Infraestrutura Escolar",
  "description": "Relatório sobre o estado da infraestrutura da escola, com propostas de melhorias.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 6
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório do Evento Anual da Escola",
  "description": "Resumo e avaliação do evento anual realizado pela escola, incluindo participação dos alunos e pais.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 7
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório de Resultados de Provas",
  "description": "Relatório sobre os resultados das provas realizadas pelos alunos no 2º semestre.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 8
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório de Monitoramento de Alunos",
  "description": "Relatório de monitoramento dos alunos baseado no desempenho acadêmico e comportamental.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 9
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Relatório de Participação dos Pais",
  "description": "Análise da participação dos pais em reuniões e atividades escolares ao longo do ano de 2024.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}

###

# Criar Relatório 10
POST http://localhost:4000/reports
Content-Type: application/json

{
  "title": "Plano Pedagógico para 2024",
  "description": "Relatório detalhando as diretrizes do plano pedagógico para o ano letivo de 2024.",
  "creatorId":"cm1n1gecd0000p20tk2szib7u"
}



# Buscar todos os relatórios com os valores padrão (page = 1, limit = 10)
GET http://localhost:4000/reports
Content-Type: application/json

###

# Buscar relatórios com paginação (page 2, limit 5)
GET http://localhost:4000/reports?page=5&limit=5
Content-Type: application/json

###

# Buscar relatórios ordenados por título em ordem crescente
GET http://localhost:4000/reports?orderBy=title&order=asc
Content-Type: application/json

###

# Buscar relatórios ordenados por data de criação (createdAt) em ordem decrescente
GET http://localhost:4000/reports?orderBy=createdAt&order=desc
Content-Type: application/json

###

# Buscar relatórios com paginação (page 3, limit 10), ordenados por data de atualização (updatedAt) em ordem ascendente
GET http://localhost:4000/reports?page=3&limit=10&orderBy=updatedAt&order=asc
Content-Type: application/json
