### Create a new subject class record
POST http://localhost:4000/subjectclass
Content-Type: application/json

{
  "userId": "cm1n1gecd0000p20tk2szib7u",
  "classId": "cm1tjn9v90000lcun072sazcw",
  "subjectId": "cm20szuwp0000skf747cab72c"
}

###

### Get all subject class records
GET http://localhost:4000/subject-class

###

### Get a specific subject class record by user ID, class ID, and subject ID
GET http://localhost:4000/subject-class/{{userId}}/{{classId}}/{{subjectId}}

###

### Delete a subject class record
DELETE http://localhost:4000/subject-class/{{userId}}/{{classId}}/{{subjectId}}
