### Create a new studying record
POST https://redesigned-space-halibut-6q54j964xrgcxrv6-4000.app.github.dev/studings
Content-Type: application/json

{
  "userId": "cm1p48x8500059wjnz9rcabvv",
  "classId": "cm1mnpepx0007vla9w6a8zgl0"
}

###

### Get all studying records
GET http://localhost:3000/studing

###

### Get a specific studying record by user ID and class ID
GET http://localhost:3000/studing/{{userId}}/{{classId}}

###

### Delete a studying record
DELETE http://localhost:3000/studing/{{userId}}/{{classId}}
