### Create a new studying record
POST http://localhost:4000/studying
Content-Type: application/json

{
  "usersId": [
    "cm1p486hq00029wjnzzn9ain8",
    "cm1p49e1m00079wjnze0vo4u1",
    "cm1p48x8500059wjnz9rcabvv"
  ],
  "classeId": "cm1mnp7h90006vla9fdq71vgn"
}

###

### Get all studying records
GET http://localhost:4000/studying

###

### Get a specific studying record by user ID and class ID
GET http://localhost:4000/studing/{{userId}}/{{classId}}

###

### Delete a studying record
DELETE http://localhost:4000/studing/{{userId}}/{{classId}}
