### Create a new studying record
POST http://localhost:4000/studing
Content-Type: application/json

{
  "usersId": [
    "cm1p486hq00029wjnzzn9ain8",
    "cm1p486hq00029wjnzzn9ain8",
    "cm1p486hq00029wjnzzn9ain8"
  ],
  "classId": "cm1mnp7h90006vla9fdq71vgn"
}

###

### Get all studying records
GET http://localhost:4000/studing

###

### Get a specific studying record by user ID and class ID
GET http://localhost:4000/studing/{{userId}}/{{classId}}

###

### Delete a studying record
DELETE http://localhost:4000/studing/{{userId}}/{{classId}}
